### ISSUE TITLE
Where i find the required app?

### ISSUE THREAD

**Issue by Zull1n0** [redaelli/imago-forensics#5]
This is the error that i received after imago launch.
I have not installed the required app because I can't find them.
Can you help me?

Traceback (most recent call last):
  File "/usr/local/bin/imago", line 10, in <module>
    sys.exit(main())
  File "/home/cesco/.local/lib/python2.7/site-packages/imago/imago.py", line 48, in main
    helper.initialize_sqli()
  File "/home/cesco/.local/lib/python2.7/site-packages/imago/helper.py", line 15, in initialize_sqli
    conn = sqlite3.connect('metadata.db')
sqlite3.OperationalError: unable to open database file

**Comment by redaelli** [comment]
Did you try?
`$ pip install imago`

**Comment by Zull1n0** [comment]
I I tried that instruction and after a reboot, imago started correctly from the command line.
I tried some numbers but every search was negative.
Could you suggest me a census number, just to see what imago returns?
Thanks
Regards

**Comment by redaelli** [comment]
Not an issue
